version: '3'
services:
  confluence:
    build:
      context: ./docker/confluence/
    container_name: confluence
    volumes:
      - confluence_data:/var/atlassian/application-data/confluence
    ports:
        - "8090:8090"
        - "8091:8091"
  postgresql:
    image: postgres:9.6
    restart: always
    container_name: confluence_postgres
    environment:
      - "POSTGRES_USER=confluence"
      - "POSTGRES_PASSWORD=secret"
      - "POSTGRES_DB=confluence"
    ports:
      - "5432:5432"
    volumes: 
      - pgdata:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - "9080:8080"
  nginx:
    build: ./docker/confluence/
    image: nginx:0.1
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./etc/nginx/conf.d:/etc/nginx/conf.d
    restart: always
volumes:
  confluence_data:
  pgdata: