version: '3'
services:
  confluence:
    build:
      context: ./
      dockerfile: confluence.dockerfile
    container_name: confluence
    volumes:
      - confluence_data:/var/atlassian/application-data/confluence
    ports:
        - "8090:8090"
        - "8091:8091"
  postgresql:
    image: postgres:9.6
    restart: always
    container_name: confluence_postgres
    environment:
      - "POSTGRES_USER=confluence"
      - "POSTGRES_PASSWORD=secret"
      - "POSTGRES_DB=confluence"
    ports:
      - "5432:5432"
    volumes: pgdata:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
volumes:
  pgdata:
  confluence_data: