version: '3'
services:

  # The Application
  confluence:
    build:
      context: ./
      dockerfile: confluence.dockerfile
    container_name: confluence
    volumes:
      - ./data/:/var/atlassian/application-data/confluence
    ports:
        - "8090:8090"
        - "8091:8091"
  postgresql:
    image: postgres:9.6
    container_name: confluence_postgres
    environment:
      - "POSTGRES_USER=confluence"
      - "POSTGRES_PASSWORD=secret"
      - "POSTGRES_DB=confluence"
    ports:
      - "5432:5432"